### ISSUE TITLE
Invalid authentication error

### ISSUE THREAD

**Issue by djfanatix** [taarskog/home-assistant-component-somweb#16]
## System Information

version | core-2023.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | pending
GitHub Web | ok
GitHub API Calls Remaining | 3120
Installed Version | 1.32.1
Stage | running
Available Repositories | 1294
Downloaded Repositories | 66

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 95.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | pending
installed_addons | File editor (5.6.0), Grafana (9.0.3), InfluxDB (4.7.0), Terminal & SSH (9.7.1), MariaDB (2.6.1), SQLite Web (3.9.2), Check Home Assistant configuration (3.11.0), evcc (0.118.11), Glances (0.19.2), Advanced SSH & Web Terminal (15.0.7), Eufy Security Add-on (1.3.0), RTSP Simple Server Add-on (v0.17.6), ESPHome (2023.8.2), TasmoAdmin (0.25.0), Samba share (10.0.2), Samba Backup (5.2.0), Node-RED (14.4.5), Z-Wave JS UI (1.15.6), Z-Wave JS (0.1.87), DSMR Reader (1.10.1), Metabase (0.5.0), TimescaleDB (3.0.2), Studio Code Server (5.10.1), Mosquitto broker (6.2.1), modbus-proxy (1.0.15), diyHue (2.0.9), Cloudflared (4.2.3), EMHASS (0.3.16), Scrypted (18-jammy-full.s6-v0.41.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 25
views | 33
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 juli 2023 om 09:12
-- | --
current_recorder_run | 22 augustus 2023 om 15:51
estimated_db_size | 11037.96 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | pending
-- | --
remaining_requests | 8
rooftop_site_count | 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | pending
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/taarskog/home-assistant-component-somweb/issues?q=is%3A+issue+label%3Abug)..

### Describe the issue

Cannot login, error 'Invalid authentication'

I tried the Somweb integration, but I cannot get passed authentication.
I can access (local and cloud) the somweb device with the login and password, but not thru the HACS integration.

If I use the forked (old) version (https://github.com/SilverXXX/home-assistant-somweb), it works.
What is the difference? Is the old version cloud and the new version a local version?

Any ideas?

### Reproduction steps

1. add integration
2.
3.
...

### Debug logs

```Text
Nothing seen in debug log
```

**Comment by taarskog** [comment]
This error may appear if:
1. either username or password is not set
2. authentication fails.

If you have values in both username and password and get this error it means that the device is found to be alive (i.e., the UDI is valid) but authentication with the provided values fail. Please double check username/password.

Please also validate that Somweb is updated with the most recent firmware.

You should typically see error messages in your log for failed authentications including a reason.

One final thing. It shouldn't matter, but have not been tested thoroughly - what language is set on your Somweb account? If it is something else than English please try to change it to English just to verify that language is not the issue.

**Comment by djfanatix** [comment]
You can close this, it is working now.

Honestly I don't know what did the trick, overwrite the forked version (with working authentication) with your version.

Or the upgrading to the latest fw version.

Many thanks for the integration and quick response

**Comment by taarskog** [comment]
Maybe not the fastest response on my part, but anyways glad to hear it is working now
